# **First Experiment**

___

In [1]:
import nltk

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Achyu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Achyu\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Achyu\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [2]:
import mlflow
import pandas as pd
import numpy as np
import mlflow.sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

c:\Users\Achyu\OneDrive\Desktop\Anaconda\envs\atlas\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.head()

                                              review sentiment
0  Every great gangster movie has under-currents ...  positive
1  I just saw this film last night, and I have to...  positive
2  This film is mildly entertaining if one neglec...  negative
3  Quentin Tarantino's partner in crime Roger Ava...  negative
4  I sat through this on TV hoping because of the...  negative

## **Data preprocessing**

In [5]:
# def lemmatization(text):
#     """Lemmatize the text"""
#     lemmatizer = WordNetLemmatizer()
#     text = text.split()
#     text = [lemmatizer.lemmatize(word) for word in text]
#     return " ".join(text)

In [6]:
# def remove_stop_words(text):
#     """Remove the stop words from the text"""
#     stop_words = set(stopwords.words("english"))
#     text = [word for word in str(text).split() if word not in stop_words]
#     return " ".join(text)

In [7]:
# def removing_numbers(text):
#     """Remove numbers from text"""
#     text = ' '.join([char for char in text if not char.isdigit()])
#     return text

In [8]:
# def lower_case(text):
#     """Convert text to lower case"""
#     text = text.split()
#     text = [word.lower() for word in text]
#     return " ".join(text)

In [9]:
# def remove_punctuations(text):
#     """Reomving the punctuations"""
#     text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
#     text = text.replace(":", "")
#     text = re.sub('\s+', ' ', text).strip()
#     return text

In [10]:
# def remove_url(text):
#     """Removing the URLs in text"""
#     url_pattern = re.compile(r'https?://\S+|www\.\S+')
#     return url_pattern.sub(r'', text)

In [11]:
# def normalize_text(df):
#     """Normalize the text data."""
#     try:
#         df['review'] = df['review'].apply(lower_case)
#         df['review'] = df['review'].apply(remove_stop_words)
#         df['review'] = df['review'].apply(removing_numbers)
#         df['review'] = df['review'].apply(remove_punctuations)
#         df['review'] = df['review'].apply(remove_url)
#         df['review'] = df['review'].apply(lemmatization)
#         return df
#     except Exception as e:
#         print(f'Error during text normalization: {e}')
#         raise

In [12]:
def lemmatization(text):
    """Lemmatize the text."""
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    """Remove stop words from the text."""
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def removing_numbers(text):
    """Remove numbers from the text."""
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    """Convert text to lower case."""
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def removing_punctuations(text):
    """Remove punctuations from the text."""
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def removing_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    """Normalize the text data."""
    try:
        df['review'] = df['review'].apply(lower_case)
        df['review'] = df['review'].apply(remove_stop_words)
        df['review'] = df['review'].apply(removing_numbers)
        df['review'] = df['review'].apply(removing_punctuations)
        df['review'] = df['review'].apply(removing_urls)
        df['review'] = df['review'].apply(lemmatization)
        return df
    except Exception as e:
        print(f'Error during text normalization: {e}')
        raise

In [13]:
df = normalize_text(df)
df.head()

                                              review sentiment
0  every great gangster movie under current human...  positive
1  saw film last night say loved every minute tak...  positive
2  film mildly entertaining one neglect acknowled...  negative
3  quentin tarantino s partner crime roger avary ...  negative
4  sat tv hoping name would worth time but dear g...  negative

In [14]:
df['sentiment'].value_counts()

sentiment
negative    269
positive    231
Name: count, dtype: int64

In [15]:
x = df['sentiment'].isin(['positive','negative'])
df = df[x]

In [16]:
df['sentiment'] = df['sentiment'].map({'positive': 1, "negative": 0})
df.head()

                                              review  sentiment
0  every great gangster movie under current human...          1
1  saw film last night say loved every minute tak...          1
2  film mildly entertaining one neglect acknowled...          0
3  quentin tarantino s partner crime roger avary ...          0
4  sat tv hoping name would worth time but dear g...          0

In [17]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [18]:
df['review'].head(10)

0    every great gangster movie under current human...
1    saw film last night say loved every minute tak...
2    film mildly entertaining one neglect acknowled...
3    quentin tarantino s partner crime roger avary ...
4    sat tv hoping name would worth time but dear g...
5    everything movie wrong wrong wrong take mike m...
6    no no no no no no no film excuse show people d...
7    possibly worst film within genre existence ann...
8    see people giving film negative review loved m...
9    got subjected pile one wednesday afternoon mot...
Name: review, dtype: object

In [19]:
# Remove empty documents
df = df[df['review'].str.strip() != '']
df = df[df['review'].str.len() > 0]
print(f"Remaining documents after filtering: {len(df)}")

Remaining documents after filtering: 500

In [29]:
vectorizer = CountVectorizer(max_features=50)
x = vectorizer.fit_transform(df['review'])
y = df['sentiment']

In [33]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
import dagshub

mlflow.set_tracking_uri('https://dagshub.com/Achyuth666/MLOps-Capstone-Project.mlflow')
dagshub.init(repo_owner="Achyuth666", repo_name="MLOps-Capstone-Project", mlflow=True)

mlflow.set_experiment("Logistic Regression Baseline")

2026-05-08 13:55:13,105 - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/Achyuth666/MLOps-Capstone-Project "HTTP/1.1 200 OK"

Initialized MLflow to track repo "Achyuth666/MLOps-Capstone-Project"

2026-05-08 13:55:13,112 - INFO - Initialized MLflow to track repo "Achyuth666/MLOps-Capstone-Project"

Repository Achyuth666/MLOps-Capstone-Project initialized!

2026-05-08 13:55:13,115 - INFO - Repository Achyuth666/MLOps-Capstone-Project initialized!

<Experiment: artifact_location='mlflow-artifacts:/d67241723bc34485850beec35f96c44d', creation_time=1778227972797, experiment_id='0', last_update_time=1778227972797, lifecycle_stage='active', name='Logistic Regression Baseline', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [36]:
import mlflow
import logging
import os
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

logging.info("Starting MLflow run...")

with mlflow.start_run():
    start_time = time.time()
    
    try:
        logging.info("Logging preprocessing parameters...")
        mlflow.log_param("vectorizer", "Bag of Words")
        mlflow.log_param("num_features", 50)
        mlflow.log_param("test_size", 0.3)

        logging.info("Initializing Logistic Regression model...")
        model = LogisticRegression(max_iter=1000)  # Increase max_iter to prevent non-convergence issues

        logging.info("Fitting the model...")
        model.fit(X_train, y_train)
        logging.info("Model training complete.")

        logging.info("Logging model parameters...")
        mlflow.log_param("model", "Logistic Regression")

        logging.info("Making predictions...")
        y_pred = model.predict(X_test)

        logging.info("Calculating evaluation metrics...")
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        logging.info("Logging evaluation metrics...")
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        logging.info("Saving and logging the model...")
        mlflow.sklearn.log_model(model, "model")

        # Log execution time
        end_time = time.time()
        logging.info(f"Model training and logging completed in {end_time - start_time:.2f} seconds.")

        # Save and log the notebook
        # notebook_path = "exp1_baseline_model.ipynb"
        # logging.info("Executing Jupyter Notebook. This may take a while...")
        # os.system(f"jupyter nbconvert --to notebook --execute --inplace {notebook_path}")
        # mlflow.log_artifact(notebook_path)

        # logging.info("Notebook execution and logging complete.")

        # Print the results for verification
        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")

    except Exception as e:
        logging.error(f"An error occurred: {e}", exc_info=True)

2026-05-08 13:57:26,361 - INFO - Starting MLflow run...
2026-05-08 13:57:27,986 - INFO - Logging preprocessing parameters...
2026-05-08 13:57:29,176 - INFO - Initializing Logistic Regression model...
2026-05-08 13:57:29,178 - INFO - Fitting the model...
2026-05-08 13:57:29,206 - INFO - Model training complete.
2026-05-08 13:57:29,207 - INFO - Logging model parameters...
2026-05-08 13:57:29,596 - INFO - Making predictions...
2026-05-08 13:57:29,598 - INFO - Calculating evaluation metrics...
2026-05-08 13:57:29,610 - INFO - Logging evaluation metrics...
2026-05-08 13:57:31,347 - INFO - Saving and logging the model...
2026/05/08 13:57:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/08 13:57:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026-05-08 13:57:43,991 - INFO - Model training and logging completed in 16.01 seconds.
2026-05-08 13:57:43,993 - INFO - Accuracy: 0.69
2026-05-08 13:57:43,994 - INFO - Precision: 0.7209302325581395
2026-05-08 13:57:43,996 - INFO - Recall: 0.62
2026-05-08 13:57:43,997 - INFO - F1 Score: 0.6666666666666666

🏃 View run industrious-fowl-44 at: https://dagshub.com/Achyuth666/MLOps-Capstone-Project.mlflow/#/experiments/0/runs/4104473a152448f6a233b292cd2f23cf
🧪 View experiment at: https://dagshub.com/Achyuth666/MLOps-Capstone-Project.mlflow/#/experiments/0